### ISSUE TITLE
[Bug] Incorrect navigation from the entry page to the documentation menu

### ISSUE THREAD

**Issue by MoonkiHong** [osori-db/osori-db.github.io#3]
- Issue definition
  - When try to navigate to the documentation menu from the entry page, some of them are not navigated correctly and represent the cumbersome (another) entry page instead.
  - Problematic menu
    - License, News, Motivation, Members, Logo, User Tips, OSORI License and Notice, Notice on Usage Restriction by Heavy Traffic, No Warranty, 
- Reproduction path
  - Path 1: Entry page (Eng/Kor) > Click the given menu on the top right.
  - Path 2: Entry page (Eng/Kor) > Click the given menu in the bottom.
  - Path 3: Documentation side menu on the left (Eng/Kor, document page) > Click the given menu on the left.
- Expected operation
  - Navigate the given documentation menu properly.
  - When it comes to the subordinate menu, it should be their single parent menu document, but navigate its subordinate section in the given documentation instead.

**Comment by fesfojas** [comment]
Good afternoon Moonki! :) Thank you for filing this issue. I will take a look at it and will inform on this thread once it is resolved.

**Comment by MoonkiHong** [comment]
Verified that this is fixed. Thank you.
